# Generated by Django 5.1.2 on 2025-05-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_comentarios_usuario_alter_encuesta_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
